### ISSUE TITLE
Add support for YAML as the media type for the fuseml-core REST API

### ISSUE THREAD

**Issue by stefannica** [fuseml/fuseml#58]
Given that most of the 3rd party tools we're integrating with all use yaml for their APIs, we should use the same for the FuseML REST API. Combining json and yaml will look really messy.

**Comment by flaviodsr** [comment]
Goa supports replacing the default response encoder and request decoder by writing an implementation for the Encoder/Decoder interfaces and for the encoder/decoder constructor functions with the following signatures:

- `func(ctx context.Context, w http.ResponseWriter) (goahttp.Encoder, error)`
- `func(r *http.Request) (goahttp.Decoder, error)`

where `goahttp` is an alias for the package with path `goa.design/goa/v3/http` (see [HTTP Encoding](https://goa.design/implement/encoding/)).

I was able to implement those interfaces to accept the content-type `application/x-yaml` and returning  a [YAML Encoder](https://pkg.go.dev/gopkg.in/yaml.v2#Encoder)/[YAML Decoder](https://pkg.go.dev/gopkg.in/yaml.v2#Decoder). In case of a different content-type the function returns the default Goa `RequestDecoder`/`ResponseEncoder`. In that way, we add support for YAML (and set it as default) without losing support for the Econders/Decoders offered by Goa.

Keep in mind that for submitting a request with a YAML body with `curl` you will need to pass the data using the `--data-binary` parameter instead of just `--data` as the last does not preserve the `\n` needed by YAML.
