### ISSUE TITLE
Codesets: separate location argument out of the API

### ISSUE THREAD

**Issue by jsuchome** [fuseml/fuseml#61]
In current implementation of codesets, https://github.com/fuseml/fuseml-core/pull/8 

"location is still showing in the REST API as a POST op parameter. I think the only way to avoid this is to leave it out of the goa design spec completely and add it manually only as a CLI command line parameter, given that the location only makes sense on the client side."

**Comment by jsuchome** [comment]
OK, so I gave up, at least for now.

If I let the location argument anywhere near the design files, it will end in the REST API definition.

When I try to modify just the client files to parse extra arguments explicitly, it does not seem to end well. It would probably work to add a new global argument, but that's just as ugly as not doing anything.
Trying to add location argument on the level of "codeset" command means it is parsed by generated code which only cares about the stuff defined in design areas. In other words, it seems I'd need to modify generated code for that which is a no go.

**Comment by stefannica** [comment]
@jsuchome I haven't looked closely at the CLI implementation, so my point of view is mostly theoretical, but here it is anyway. 

First of all, I'm pretty sure this change needs to go into the CLI main package. Not in the goa design, nor in the generated client nor the server code files. I'm aware that the CLI main package has also been initially generated from the goa design, but we can and should alter it now to suit our needs. It just has to be modified to accept an additional command line parameter to the `codeset push` command that doesn't come from the generated design.

However, that might not be possible without changing the generated code, because I see goa is generating not just the data structures and serialization/deserialization client logic, but also the CLI command line arguments every time it is invoked (in `gen/http/cli` and `gen/grpc/cli`. I think this is where the problem lies: goa should generate those only when the CLI code is first generated, as part of the `main` CLI package.

I suggest you make a copy of that `gen/http/cli` code into the main CLI package, alter it to suit our needs and use that instead of the generated one.

**Comment by jsuchome** [comment]
Exactly, the problem is not with cli `main.go`, but with (generated) `gen/http/cli` where the validation of arguments happen.

You solution might indeed work; I'm not sure it is worth it, but well, it could be the way.

**Comment by stefannica** [comment]
Fixed by: https://github.com/fuseml/fuseml-core/pull/63
